@startmindmap
* 0
** 4
*** 1
**** 2
***** 1
****** 9
******* 9
******** 8
********* 0
********** 3
*********** Bob
***** 5
****** 7
******* 8
******** 4
********* 4
********** 0
*********** Alice
*** 6
**** 8
***** 8
****** 9
******* 2
******** 0
********* 1
********** 1
*********** patate
* 1
** 1
*** 2
**** Urgences
** 5
*** SAMU
@endmindmap
