name: CI

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

jobs:
  ci:
    name: check fmt clippy test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal --component clippy,rustfmt
          rustup default stable

      - name: cargo check
        run: cargo check --all-targets --all-features

      - name: cargo fmt --check
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: cargo test
        run: cargo test --all-targets --all-features